[tool.poetry]
name = "jupyter"
version = "0.1.0"
description = ""
authors = ["crazyboy9103 <gil9103@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
ipykernel = "^6.22.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
